// Bahasa Malaysia → English dictionary for inline UI strings.
// Auto-generated and curated. Keys are exact source strings (trimmed).
export const TX_DICT: Record<string, string> = {
  // ===== Common verbs / actions =====
  'Simpan': 'Save',
  'Batal': 'Cancel',
  'Padam': 'Delete',
  'Edit': 'Edit',
  'Hantar': 'Send',
  'Sahkan': 'Confirm',
  'Salin': 'Copy',
  'Pilih': 'Select',
  'Pilih Semua': 'Select All',
  'Cuba Lagi': 'Try Again',
  'Cuba sekarang': 'Try now',
  'Seterusnya': 'Next',
  'Kembali ke Kerja': 'Back to Jobs',
  'Tindakan Tidak Boleh Dibatalkan': 'Action Cannot Be Undone',
  'Tindakan ini tidak boleh dibatalkan.': 'This action cannot be undone.',
  'Tindakan ini tidak boleh dibatalkan. Laporan dan semua maklumatnya akan dipadam.':
    'This action cannot be undone. The report and all its data will be deleted.',
  'Tindakan ini tidak boleh dibatalkan. Sebut harga dan invois berkaitan tidak akan dipadam.':
    'This action cannot be undone. Related quotations and invoices will not be deleted.',
  'Memuatkan...': 'Loading...',
  'Menghantar...': 'Sending...',
  'Sila tunggu…': 'Please wait…',
  'Ralat': 'Error',
  'Ralat menyimpan': 'Error saving',
  'Ralat membuat invois': 'Error creating invoice',
  'Gagal simpan': 'Failed to save',
  'Gagal kongsi': 'Share failed',
  'Gagal kongsi PDF': 'Failed to share PDF',
  'Gagal kongsi laporan': 'Failed to share report',
  'Gagal kongsi resit': 'Failed to share receipt',
  'Gagal memadam laporan': 'Failed to delete report',
  'Gagal membatalkan langganan. Sila cuba lagi.': 'Failed to cancel subscription. Please try again.',
  'Gagal memuat naik PDF. Semak sambungan internet anda.':
    'Failed to upload PDF. Check your internet connection.',
  'Gagal mengaktifkan semula langganan': 'Failed to reactivate subscription',
  'Gagal mengesahkan': 'Failed to verify',
  'Gagal menggunakan bulan percuma': 'Failed to apply free months',
  'Gagal menghantar balasan': 'Failed to send reply',
  'Gagal menghantar invois': 'Failed to send invoice',
  'Gagal menghantar tiket. Sila cuba lagi.': 'Failed to submit ticket. Please try again.',
  'Gagal menjana laporan': 'Failed to generate report',
  'Gagal menjana pautan. Semak sambungan internet anda.':
    'Failed to generate link. Check your internet connection.',
  'Gagal menjana pratonton resit': 'Failed to generate receipt preview',
  'Gagal muat naik QR': 'Failed to upload QR',
  'Gagal muat naik logo': 'Failed to upload logo',
  'Gagal kemaskini status.': 'Failed to update status.',

  // ===== Navigation / titles =====
  'Tetapan': 'Settings',
  'Kerja': 'Jobs',
  'Pelanggan': 'Customers',
  'Sebut Harga': 'Quotation',
  'Invois': 'Invoice',
  'Resit': 'Receipt',
  'Laporan': 'Report',
  'Laporan Ringkasan': 'Summary Report',
  'Laporan Siap Kerja': 'Completion Report',
  'Pelanggan Aktif': 'Active Customers',

  // ===== Buttons =====
  'Simpan Profil': 'Save Profile',
  'Simpan Kerja': 'Save Job',
  'Simpan Pelanggan': 'Save Customer',
  'Simpan Akaun': 'Save Account',
  'Simpan Draf': 'Save Draft',
  'Simpan Draft': 'Save Draft',
  'Simpan QR': 'Save QR',
  'Simpan Terma Invois': 'Save Invoice Terms',
  'Simpan Terma Sebut Harga': 'Save Quotation Terms',
  'Simpan Terma Work Order': 'Save Work Order Terms',
  'Simpan Tetapan LHDN': 'Save LHDN Settings',
  'Simpan Tetapan Nombor': 'Save Numbering Settings',
  'Simpan maklumat pelanggan': 'Save customer info',
  'Tambah Item': 'Add Item',
  'Tambah Kerja': 'Add Job',
  'Tambah Akaun Bank': 'Add Bank Account',
  'Tambah Pelanggan Baru': 'Add New Customer',
  'Tambah Pelanggan Pertama': 'Add Your First Customer',
  'Tambah QR Payment': 'Add QR Payment',
  'Tambah dalam Tetapan': 'Add in Settings',
  'Tambah maklumat atau tanya soalan lanjut...': 'Add more details or ask a follow-up question...',
  'Tandakan Selesai': 'Mark Complete',
  'Tandakan jika invois ini telah dihantar ke portal MyInvois LHDN':
    'Tick if this invoice has been submitted to the LHDN MyInvois portal',

  // ===== Job / customer / invoice page bits =====
  'Kerja Baru': 'New Job',
  'Pelanggan Baru': 'New Customer',
  'Invois Baru': 'New Invoice',
  'Sebut Harga Baru': 'New Quotation',
  'Work Order Baru': 'New Work Order',
  'Buat Invois': 'Create Invoice',
  'Buat Invois Baru': 'Create New Invoice',
  'Buat Kerja Baru': 'Create New Job',
  'Buat Laporan Siap Kerja': 'Create Completion Report',
  'Buat Sebut Harga': 'Create Quotation',
  'Buat Sebut Harga Baru': 'Create New Quotation',
  'Buat Tiket Baru': 'Create New Ticket',
  'Buat Work Order': 'Create Work Order',
  'Buat Work Order Baru': 'Create New Work Order',
  'Edit Invois': 'Edit Invoice',
  'Edit Kerja': 'Edit Job',
  'Edit Laporan': 'Edit Report',
  'Edit Pelanggan': 'Edit Customer',
  'Edit Sebut Harga': 'Edit Quotation',
  'Edit Work Order': 'Edit Work Order',
  'Kemaskini Invois': 'Update Invoice',
  'Kemaskini Kerja': 'Update Job',
  'Kemaskini Pelanggan': 'Update Customer',
  'Kemaskini Sebut Harga': 'Update Quotation',
  'Lihat Invois': 'View Invoice',
  'Lihat Invois →': 'View Invoice →',
  'Lihat Laporan': 'View Report',
  'Lihat Sebut Harga': 'View Quotation',
  'Lihat Sebut Harga →': 'View Quotation →',
  'Lihat Work Order →': 'View Work Order →',
  'Lihat invois →': 'View invoice →',
  'Lihat sebut harga →': 'View quotation →',
  'Hantar Invois': 'Send Invoice',
  'Hantar Sebut Harga': 'Send Quotation',
  'Hantar Laporan': 'Send Report',
  'Hantar Tiket': 'Submit Ticket',
  'Hantar Balasan': 'Send Reply',
  'Hantar kepada Pelanggan': 'Send to Customer',
  'Kongsi via WhatsApp': 'Share via WhatsApp',
  'Kongsi quotation via WhatsApp': 'Share quotation via WhatsApp',
  'Kongsi Resit via WhatsApp': 'Share Receipt via WhatsApp',
  'Kongsi Semula via WhatsApp': 'Re-share via WhatsApp',

  // ===== Empty states =====
  'Belum ada kerja': 'No jobs yet',
  'Belum ada pelanggan': 'No customers yet',
  'Belum ada invois': 'No invoices yet',
  'Belum ada sebut harga': 'No quotations yet',
  'Belum ada work order': 'No work orders yet',
  'Belum ada laporan siap kerja': 'No completion reports yet',
  'Belum ada resit. Resit dijana automatik bila invois ditandakan dibayar.':
    'No receipts yet. Receipts are generated automatically when invoices are marked paid.',
  'Belum ada rujukan': 'No referrals yet',
  'Belum ada kaedah pembayaran.': 'No payment methods yet.',
  'Belum Dihantar': 'Not Sent',
  'Tiada Logo': 'No Logo',
  'Tiada Work Order untuk kerja ini.': 'No Work Orders for this job.',
  'Tiada invois dijumpai': 'No invoices found',
  'Tiada kerja dijumpai': 'No jobs found',
  'Tiada kerja untuk pelanggan ini': 'No jobs for this customer',
  'Tiada laporan dijumpai': 'No reports found',
  'Tiada pelanggan': 'No customers',
  'Tiada pelanggan dijumpai': 'No customers found',
  'Tiada resit dijumpai': 'No receipts found',
  'Tiada respons lagi. Kami akan balas dalam masa 24 jam.':
    'No reply yet. We will respond within 24 hours.',
  'Tiada sebut harga dijumpai': 'No quotations found',
  'Tiada tag': 'No tags',
  'Tiada work order dijumpai': 'No work orders found',
  'Tiada konfigurasi diperlukan — semua pautan dijana automatik.':
    'No configuration needed — all links are generated automatically.',

  // ===== Search placeholders =====
  'Cari kerja...': 'Search jobs...',
  'Cari kerja, nombor, atau pelanggan...': 'Search by job, number, or customer...',
  'Cari nama atau nombor telefon...': 'Search by name or phone...',
  'Cari nama atau telefon...': 'Search by name or phone...',
  'Cari nombor atau pelanggan...': 'Search by number or customer...',
  'Cari nombor resit, invois, atau pelanggan...':
    'Search by receipt number, invoice, or customer...',
  'Cari nombor, tajuk, atau pelanggan...': 'Search by number, title, or customer...',

  // ===== Form fields & placeholders =====
  'Nama': 'Name',
  'Nama:': 'Name:',
  'Tanpa Nama': 'No name',
  'Alamat': 'Address',
  'Alamat lengkap...': 'Full address...',
  'Alamat syarikat (pilihan)': 'Company address (optional)',
  'Nota': 'Notes',
  'Nota:': 'Notes:',
  'Nota Dalaman': 'Internal Notes',
  'Nota Tambahan / Catatan Tapak': 'Additional Notes / Site Remarks',
  'Nota tambahan untuk pelanggan...': 'Additional notes for the customer...',
  'Nota untuk rujukan dalaman...': 'Notes for internal reference...',
  'Sebarang catatan atau nota juruteknik...': 'Any technician remarks or notes...',
  'Kategori': 'Category',
  'Kategori Isu *': 'Issue Category *',
  'Kategori Kerja': 'Job Category',
  'Kategori:': 'Category:',
  'Tarikh:': 'Date:',
  'Tarikh Dibayar': 'Paid Date',
  'Tarikh Dibayar:': 'Paid Date:',
  'Tarikh Dijadualkan': 'Scheduled Date',
  'Tarikh Invois': 'Invoice Date',
  'Tarikh Mula': 'Start Date',
  'Tarikh Siap': 'Completion Date',
  'Tarikh Siap Anggaran': 'Estimated Completion Date',
  'Tarikh Siap Kerja *': 'Completion Date *',
  'Pilih tarikh...': 'Select date...',
  'Pilih kerja...': 'Select job...',
  'Pilih pelanggan...': 'Select customer...',
  'Pilih kerja': 'Select job',
  'Pilih pelanggan': 'Select customer',
  'Pilih tarikh': 'Select date',
  'Pilih Templet': 'Select Template',
  'Pilih kaedah pembayaran yang akan dipaparkan dalam invois ini':
    'Choose the payment method to display on this invoice',
  'Pilih pelan yang sesuai': 'Choose the right plan',
  'Pilih tempoh pembaharuan': 'Choose renewal period',
  'Guna Tarikh Ini': 'Use This Date',

  // ===== Job form labels =====
  'Tajuk Kerja *': 'Job Title *',
  'Tajuk diperlukan': 'Title is required',
  'Skop Kerja': 'Scope of Work',
  'Skop Kerja *': 'Scope of Work *',
  'Skop kerja diperlukan': 'Scope of work is required',
  'Status Kerja': 'Job Status',
  'Item Kerja': 'Work Items',
  'Item Kerja *': 'Work Items *',
  'Lokasi Kerja': 'Job Location',
  'Maklumat Kerja': 'Job Info',
  'Sejarah Kerja': 'Job History',
  'Ringkasan Kerja': 'Job Summary',
  'Senarai Semak Siap Kerja': 'Completion Checklist',
  'Penerangan Kerja yang Dilaksanakan *': 'Description of Work Done *',
  'Pengesahan Pelanggan (opsional)': 'Customer Confirmation (optional)',
  'Huraikan kerja yang telah dilaksanakan secara terperinci...':
    'Describe the work performed in detail...',
  'Huraikan skop kerja secara terperinci...': 'Describe the scope of work in detail...',
  'Huraikan skop kerja...': 'Describe the scope of work...',
  // 'Pelanggan' duplicated above (line ~56) — picked the dominant translation.
  'Pelanggan *': 'Customer *',
  'Kerja *': 'Job *',
  'Nama Pelanggan *': 'Customer Name *',
  'Sila masukkan nama pelanggan': 'Please enter the customer name',
  'Sila masukkan nombor telefon': 'Please enter a phone number',
  'Sila masukkan tajuk kerja': 'Please enter the job title',
  'Sila isi nama juruteknik': 'Please enter the technician name',
  'Sila isi penerangan kerja': 'Please enter the work description',
  'Sila isi sekurang-kurangnya satu item': 'Please add at least one item',
  'Sila isi semua medan': 'Please fill in all fields',
  'Sila lengkapkan semua medan wajib': 'Please complete all required fields',
  'Sila pilih kerja': 'Please select a job',
  'Sila pilih pelanggan': 'Please select a customer',
  'Sila pilih tarikh': 'Please select a date',
  'Sila muat naik imej QR': 'Please upload a QR image',
  'Sila muat naik sekurang-kurangnya 1 gambar selepas': 'Please upload at least 1 "after" photo',
  'Sila nyatakan sebab penolakan': 'Please state the rejection reason',
  'Sila taip "BUKA" untuk meneruskan': 'Please type "OPEN" to continue',
  'Harga tidak boleh negatif': 'Price cannot be negative',
  'Nama Juruteknik': 'Technician Name',
  'Nama Juruteknik *': 'Technician Name *',
  'Nama pekerja/juruteknik': 'Worker / technician name',
  'Nama pelanggan sebagai pengesahan': 'Customer name as confirmation',
  'Minta pelanggan taip nama sebagai tanda pengesahan kerja siap':
    'Ask the customer to type their name to confirm job completion',

  // ===== Customer form =====
  'Nombor Telefon': 'Phone Number',
  'Nombor Telefon *': 'Phone Number *',
  'Nombor telefon pelanggan tiada dalam rekod': 'Customer phone number is missing from records',
  'No. Telefon': 'Phone',
  'TIN Pelanggan': 'Customer TIN',
  'Profil Pelanggan': 'Customer Profile',
  'Ringkasan Pelanggan': 'Customer Summary',

  // ===== Settings page =====
  'Profil Syarikat': 'Company Profile',
  'Profil dan akaun syarikat': 'Company profile & account',
  'Profil berjaya dikemaskini!': 'Profile updated successfully!',
  'Nama Syarikat *': 'Company Name *',
  'Syarikat Anda': 'Your Company',
  'Maklumat ini akan dipaparkan dalam setiap invois anda':
    'This info will be displayed on every invoice',
  'Nama syarikat, telefon, alamat dan logo': 'Company name, phone, address & logo',
  'Logo Syarikat': 'Company Logo',
  'Logo Syarikat (pilihan)': 'Company Logo (optional)',
  'Logo syarikat di PDF': 'Company logo on PDFs',
  'Muat naik logo': 'Upload logo',
  'Muat Naik Imej QR': 'Upload QR Image',
  'Muat Turun PDF': 'Download PDF',
  'Muat Turun Resit': 'Download Receipt',
  'Padam Logo': 'Delete Logo',
  'Akaun bank dan QR bayaran untuk invois': 'Bank accounts & payment QR for invoices',
  'Akaun bank disimpan!': 'Bank account saved!',
  'Akaun:': 'Account:',
  'Aktifkan e-Invois LHDN': 'Enable LHDN e-Invoice',
  'Aktifkan notifikasi push pada telefon atau komputer anda':
    'Enable push notifications on your phone or computer',
  'Aktifkan untuk memaparkan medan LHDN pada invois anda':
    'Enable to display LHDN fields on your invoices',
  'Aktifkan Semula Langganan': 'Reactivate Subscription',
  'Aktifkan Semula (Percuma)': 'Reactivate (Free)',
  'Bahagian ini dijana automatik dari data dokumen sebenar dan tidak boleh diubah.':
    'This section is auto-generated from real document data and cannot be edited.',
  'Bantuan AI dan sokongan': 'AI help & support',
  'E-mel Akaun': 'Account Email',
  'Format baru SSM (nombor sahaja)': 'New SSM format (numbers only)',
  'Format dipulihkan ke lalai (nombor seterusnya tidak diubah)':
    'Format restored to default (next number unchanged)',
  'Format lama SSM (jika ada)': 'Old SSM format (if any)',
  'Format nombor auto untuk semua jenis dokumen': 'Auto-numbering format for all document types',
  'Awalan diperlukan': 'Prefix is required',
  'Nombor Akaun *': 'Account Number *',
  'Nombor Invois': 'Invoice Number',
  'Nombor Kerja': 'Job Number',
  'Nombor Sebut Harga': 'Quotation Number',
  'Nombor Seterusnya': 'Next Number',
  'Nombor seterusnya mestilah 1 atau lebih': 'Next number must be 1 or more',
  'Nombor seterusnya:': 'Next number:',
  'Nombor untuk dokumen seterusnya. Ubah jika ada dokumen luar sistem.':
    'Number for the next document. Change if you have documents from outside the system.',
  'Nama Akaun *': 'Account Name *',
  'Nama Bank': 'Bank Name',
  'Nombor akaun disalin!': 'Account number copied!',
  'No. Pendaftaran SSM (Baru)': 'SSM Registration No. (New)',
  'No. Pendaftaran SSM (Baru) mesti nombor sahaja':
    'SSM Registration No. (New) must be numbers only',
  'No. Pendaftaran SSM (Lama)': 'SSM Registration No. (Old)',
  'No. Pendaftaran SST': 'SST Registration No.',
  'No. pendaftaran SST': 'SST registration no.',
  'No. Sebut Harga': 'Quotation No.',
  'No. TIN Syarikat': 'Company TIN',
  'TIN Syarikat': 'Company TIN',
  'TIN Syarikat Anda': 'Your Company TIN',
  'Maklumat cukai dan e-Invois LHDN MyInvois': 'Tax info & LHDN MyInvois e-Invoice',
  'Untuk tujuan e-invois LHDN': 'For LHDN e-Invoice purposes',
  'Sesuaikan format nombor dokumen mengikut standard syarikat anda.':
    'Customize document number format to match your company standard.',
  'Sesuaikan ucapan & ayat penutup untuk semua mesej WhatsApp':
    'Customize greetings & closing for all WhatsApp messages',
  'Sesuaikan ucapan & ayat penutup untuk setiap mesej WhatsApp anda. Bahagian butiran (nombor':
    'Customize greetings & closing for each WhatsApp message. Detail sections (number',
  'dokumen, jumlah, pautan) dikunci supaya mesej anda sentiasa tepat.':
    'document, total, link) are locked so your message stays accurate.',
  'Templet WhatsApp untuk': 'WhatsApp template for',
  'Templet dikembalikan ke asal. Tekan Simpan untuk sahkan.':
    'Template restored to original. Press Save to confirm.',
  'Terma & syarat berjaya disimpan!': 'Terms & conditions saved!',
  'Terma & syarat invois...': 'Invoice terms & conditions...',
  'Terma & syarat sebut harga...': 'Quotation terms & conditions...',
  'Terma Work Order disimpan!': 'Work Order terms saved!',
  'Terma dipulihkan ke lalai. Tekan Simpan untuk mengesahkan.':
    'Terms restored to default. Press Save to confirm.',
  'Terma ini akan dipaparkan dalam PDF invois':
    'These terms will be displayed on the invoice PDF',
  'Terma ini akan dipaparkan dalam PDF sebut harga':
    'These terms will be displayed on the quotation PDF',
  'Terma ini dipaparkan dalam setiap Invois PDF': 'These terms appear on every Invoice PDF',
  'Terma ini dipaparkan dalam setiap Sebut Harga PDF':
    'These terms appear on every Quotation PDF',
  'Terma ini dipaparkan secara automatik dalam setiap Work Order baharu. Anda boleh edit per-dokumen ketika':
    'These terms appear automatically on every new Work Order. You can edit them per-document when',
  'membuat Work Order.': 'creating a Work Order.',
  'Tetapan LHDN disimpan!': 'LHDN settings saved!',
  'Imbas untuk membayar': 'Scan to pay',
  'Kaedah Pembayaran dalam Invois': 'Payment Methods on Invoice',
  'Kaedah bayaran di invois': 'Payment methods on invoice',
  'Kaedah pembayaran dipadam': 'Payment method removed',
  'Kod rujukan dan ganjaran bulan percuma': 'Referral code & free-month rewards',
  'Kongsi link anda dan dapatkan': 'Share your link to earn',
  'Kongsi link anda dan dapatkan 1 bulan percuma setiap kali rakan anda melanggan!':
    'Share your link to earn 1 free month every time a friend subscribes!',
  'Kongsi link untuk mula mendapat ganjaran!': 'Share your link to start earning rewards!',
  'Link Rujukan Anda:': 'Your Referral Link:',
  'Link rujukan disalin! Kongsi dengan rakan kontraktor anda.':
    'Referral link copied! Share with your contractor friends.',
  'QR payment disimpan!': 'QR payment saved!',
  'T&C untuk Sebut Harga, Invois dan Work Order': 'T&Cs for Quotation, Invoice & Work Order',
  'e-Invois': 'e-Invoice',
  'e-Invois LHDN MyInvois': 'LHDN MyInvois e-Invoice',

  // ===== LHDN / e-invoice notes =====
  'Integrasi automatik dengan MyInvois akan datang. Buat masa ini, sila hantar invois secara manual di myinvois.hasil.gov.my dan tandakan checkbox di atas setelah selesai.':
    'Automatic MyInvois integration is coming. For now, please submit invoices manually at myinvois.hasil.gov.my and tick the box above when done.',
  'Integrasi automatik dengan portal MyInvois LHDN akan datang tidak lama lagi.':
    'Automatic integration with the LHDN MyInvois portal is coming soon.',

  // ===== Bulk-action / dialog =====
  'Padam Akaun': 'Delete Account',
  'Padam Akaun WorkTrace': 'Delete WorkTrace Account',
  'Padam Invois Terpilih?': 'Delete Selected Invoices?',
  'Padam Invois?': 'Delete Invoice?',
  'Padam Kerja Terpilih?': 'Delete Selected Jobs?',
  'Padam Kerja?': 'Delete Job?',
  'Padam Laporan': 'Delete Report',
  'Padam Laporan Siap Kerja?': 'Delete Completion Report?',
  'Padam Pelanggan Terpilih?': 'Delete Selected Customers?',
  'Padam Pelanggan?': 'Delete Customer?',
  'Padam Sebut Harga Terpilih?': 'Delete Selected Quotations?',
  'Padam Sebut Harga?': 'Delete Quotation?',
  'Padam Work Order?': 'Delete Work Order?',
  'Padam akaun dan tindakan yang tidak boleh dibatalkan':
    'Delete account & irreversible actions',
  'PADAM': 'DELETE',
  'BATAL': 'CANCEL',
  'Taip BATAL di sini': 'Type CANCEL here',
  'Taip BATAL untuk mengesahkan:': 'Type CANCEL to confirm:',
  'Taip BUKA untuk mengesahkan:': 'Type OPEN to confirm:',
  'Taip PADAM di sini': 'Type DELETE here',
  'Buka Kunci Invois Dibayar?': 'Unlock Paid Invoice?',
  'Buka dalam tab baru': 'Open in new tab',
  'Sahkan Pemadaman': 'Confirm Deletion',
  'Sahkan Pembatalan': 'Confirm Cancellation',
  'Sahkan & Tandakan Dibayar': 'Confirm & Mark as Paid',
  'Sahkan & Tukar Status': 'Confirm & Change Status',
  'Sahkan Bayaran': 'Confirm Payment',
  'Sahkan Tolak': 'Confirm Rejection',
  'Sahkan bahawa pembayaran telah diterima untuk invois ini.':
    'Confirm that payment has been received for this invoice.',
  'Saya faham bahawa tindakan ini tidak boleh dibatalkan selepas 14 hari dan semua data saya akan dipadam kekal.':
    'I understand that this action cannot be undone after 14 days and all my data will be permanently deleted.',
  'Memadamkan akaun akan:': 'Deleting your account will:',
  'Data anda (kerja, pelanggan, invois) akan': 'Your data (jobs, customers, invoices) will',
  'Data pelanggan akan dipadam. Kerja berkaitan tidak akan dipadam.':
    'Customer data will be deleted. Related jobs will not be deleted.',
  'Data yang akan dipadam:': 'Data that will be deleted:',
  'Dengan membatalkan, langganan Pro anda akan tamat pada':
    'By cancelling, your Pro subscription will end on',
  '. Anda masih boleh menggunakan semua ciri Pro sehingga tarikh tersebut.':
    '. You can still use all Pro features until that date.',
  '. Selepas itu, akaun anda akan kembali ke pelan Free secara automatik.':
    '. After that, your account will automatically revert to the Free plan.',
  'Selepas pembatalan, anda akan kehilangan:': 'After cancellation, you will lose:',
  'Kekal dengan Pro': 'Keep Pro',
  'Klik butang di bawah untuk aktifkan semula tanpa perlu bayar.':
    'Click the button below to reactivate without payment.',
  'Klik untuk lanjutkan tarikh tamat langganan anda sekarang.':
    'Click to extend your subscription end date now.',
  'Langganan anda masih aktif sehingga': 'Your subscription is still active until',
  'Langganan berjaya diaktifkan semula!': 'Subscription reactivated successfully!',
  'Langkau buat masa ni': 'Skip for now',
  'Cerita sikit pasal syarikat anda': 'Tell us a bit about your company',
  'Contoh format syarikat lain:': 'Other company format examples:',
  'Cth: Resit tidak jelas, jumlah salah...': 'e.g. Receipt unclear, wrong amount...',
  'Pelanggan akan mengesahkan atau menolak melalui pautan WhatsApp yang dikongsi.':
    'The customer will confirm or reject via the WhatsApp link you share.',
  'Pelanggan berjaya dikemaskini!': 'Customer updated successfully!',
  'Pelanggan berjaya dipadam!': 'Customer deleted successfully!',
  'Pelanggan berjaya disimpan!': 'Customer saved successfully!',
  'Pelanggan tanpa had': 'Unlimited customers',
  'Pelanggan tiada nombor telefon': 'Customer has no phone number',
  'Pelanggan tidak dijumpai.': 'Customer not found.',
  'Pelayar anda tidak menyokong notifikasi. Untuk iPhone, sila pasang aplikasi ke skrin utama dahulu.':
    "Your browser doesn't support notifications. On iPhone, please install the app to your home screen first.",
  'Notifikasi telah disekat. Sila benarkan dalam tetapan pelayar anda untuk laman ini.':
    'Notifications are blocked. Please allow them in your browser settings for this site.',
  'Pasang WorkTrace untuk akses pantas dari skrin utama.':
    'Install WorkTrace for quick access from your home screen.',
  'Mod edit dibuka. Hantar semula selepas perubahan.':
    'Edit mode enabled. Resend after changes.',
  'Anda boleh mengubah suai laporan dan hantar semula.':
    'You can edit the report and resend it.',
  'Anda telah mencapai had pelan Free. Naik taraf ke Pro untuk akses tanpa had.':
    "You've hit the Free plan limit. Upgrade to Pro for unlimited access.",
  'Aplikasi tidak memenuhi keperluan': "App doesn't meet my needs",
  'Mengganggu kerja harian': 'Disrupts daily work',
  'Hilang ciri yang diperlukan': 'Missing a needed feature',
  'Tidak boleh guna langsung': "Can't use it at all",
  'Tidak guna WorkTrace lagi': 'No longer using WorkTrace',
  'Tidak guna aplikasi ini': "Don't use this app",
  'Tidak, Isi Manual': 'No, Fill Manually',
  'Kenapa anda ingin membatalkan?': 'Why do you want to cancel?',
  'Beritahu saya bila siap': 'Notify me when ready',
  '⚠️ Anda mempunyai langganan Pro aktif. Langganan akan dibatalkan serta-merta. Tiada bayaran balik untuk tempoh yang tidak digunakan.':
    '⚠️ You have an active Pro subscription. It will be cancelled immediately. No refund for unused time.',

  // ===== Job/Quotation/Invoice statuses & banners =====
  'Akan Datang': 'Coming Soon',
  'Akan Tamat ⚠️': 'Expiring ⚠️',
  'Akan datang dalam fasa seterusnya.': 'Coming in the next phase.',
  'Akaun anda akan dipadam kekal pada:': 'Your account will be permanently deleted on:',
  'Aktif': 'Active',
  'Anda': 'You',
  'Anda ada': 'You have',
  'Bayar Sebelum': 'Pay Before',
  'Bil Invois Dibayar': 'Paid Invoices',
  'Bil Kerja': 'Job Count',
  'Bukti disahkan, invois ditandakan Dibayar!':
    'Proof verified, invoice marked Paid!',
  'Bukti ditolak. Pelanggan boleh hantar semula dengan pautan baru.':
    'Proof rejected. Customer can resubmit using a new link.',
  'Bulan Digunakan': 'Months Used',
  'Bulan Diperolehi': 'Months Earned',
  'Bulan Ini': 'This Month',
  'Bulan Lepas': 'Last Month',
  'Dalam Proses': 'In Progress',
  'Dari': 'From',
  'DISIMPAN': 'SAVED',
  'Disahkan oleh pelanggan': 'Confirmed by customer',
  'Diskaun': 'Discount',
  'Download laporan yang diperlukan': 'Download the report you need',
  'Draf disimpan!': 'Draft saved!',
  'Draf invois disimpan!': 'Invoice draft saved!',
  'Draf laporan disimpan!': 'Report draft saved!',
  'Export / screenshot invois penting': 'Export / screenshot important invoices',
  // 'Format baru SSM' duplicated above
  'Gambar hasil akhir kerja yang telah disiapkan': 'Photo of the finished work',
  'Gambar keadaan sebelum kerja bermula untuk perbandingan':
    'Photo of conditions before work began (for comparison)',
  'Hubungi Sokongan via WhatsApp': 'Contact Support via WhatsApp',
  'Huruf atau kod sebelum nombor': 'Letters or code before the number',
  'Invois Belum Bayar': 'Unpaid Invoice',
  'Invois Dibayar': 'Paid Invoices',
  'Invois Sudah Wujud': 'Invoice Already Exists',
  'Invois berjaya dibuat!': 'Invoice created successfully!',
  'Invois berjaya dikemaskini!': 'Invoice updated successfully!',
  'Invois dihantar!': 'Invoice sent!',
  'Invois dihantar! WhatsApp telah dibuka.': 'Invoice sent! WhatsApp opened.',
  'Invois dipadam': 'Invoice deleted',
  'Invois ditandakan sebagai Dibayar!': 'Invoice marked as Paid!',
  'Invois ini telah ditandakan sebagai': 'This invoice is marked as',
  'Invois sudah wujud': 'Invoice already exists',
  'Invois tidak boleh dijana sebelum Laporan Siap Kerja dihantar. Laporan ini membuktikan kerja telah siap dilaksanakan sebelum pembayaran dipohon.':
    'Invoices cannot be created before the Completion Report is sent. The report proves the work was finished before payment is requested.',
  'Invois tidak dijumpai.': 'Invoice not found.',
  'Invois yang dipadam tidak boleh dipulihkan.':
    'Deleted invoices cannot be recovered.',
  'Invois yang telah dihantar atau dibayar tidak boleh dipadam.':
    'Sent or paid invoices cannot be deleted.',
  'Isi Laporan Siap Kerja': 'Fill in the Completion Report',
  'Jangan tutup halaman ini sementara kami sedang semak status langganan anda.':
    "Don't close this page while we check your subscription status.",
  'Julat tarikh tidak sah': 'Invalid date range',
  'Jumlah': 'Total',
  'Jumlah Diterima': 'Amount Received',
  'Jumlah Kerja Baru': 'New Jobs',
  'Jumlah Keseluruhan': 'Grand Total',
  'Jumlah Pelanggan': 'Total Customers',
  'Jumlah Pendapatan': 'Total Revenue',
  'Jumlah Resit': 'Total Receipts',
  'Jumlah Rujukan': 'Total Referrals',
  'Jumlah:': 'Total:',
  'Kami akan balas dalam masa 24 jam (hari bekerja).':
    'We will respond within 24 hours (working days).',
  'Kami sedang tunggu pengesahan BillPlz dan kemas kini pelan anda.':
    'We are waiting for BillPlz to confirm and update your plan.',
  'Kerja aktif tanpa had': 'Unlimited active jobs',
  'Kerja berjaya dikemaskini!': 'Job updated successfully!',
  'Kerja berjaya dipadam!': 'Job deleted successfully!',
  'Kerja berjaya disimpan!': 'Job saved successfully!',
  'Kerja ini sudah ada Work Order yang aktif. Padam atau tolak yang sedia ada sebelum buat baru.':
    'This job already has an active Work Order. Delete or reject the existing one before creating a new one.',
  'Kerja ini sudah ada invois.': 'This job already has an invoice.',
  'Kerja ini sudah mempunyai invois. Nak lihat atau buat baru?':
    'This job already has an invoice. View it or create a new one?',
  'Kerja ini sudah mempunyai invois. Setiap kerja hanya boleh ada 1 invois.':
    'This job already has an invoice. Each job can only have 1 invoice.',
  'Kerja ini sudah mempunyai sebut harga. Setiap kerja hanya boleh ada 1 sebut harga.':
    'This job already has a quotation. Each job can only have 1 quotation.',
  'Kerja tidak dijumpai.': 'Job not found.',
  'Kerja Selesai': 'Completed Jobs',
  'Laporan Dihantar': 'Report Sent',
  'Laporan Disahkan oleh Pelanggan — Kerja Selesai':
    'Report Confirmed by Customer — Job Complete',
  'Laporan Ditolak oleh Pelanggan': 'Report Rejected by Customer',
  'Laporan Siap Kerja Diperlukan': 'Completion Report Required',
  'Laporan Siap Kerja perlu disahkan oleh pelanggan dahulu':
    'The Completion Report must be confirmed by the customer first',
  'Laporan dihantar! Membuka WhatsApp...': 'Report sent! Opening WhatsApp...',
  'Laporan dimuat turun': 'Report downloaded',
  'Laporan dipadam': 'Report deleted',
  'Laporan siap kerja dibuat dari halaman kerja selepas sebut harga diterima.':
    'Completion reports are created from the job page after the quotation is accepted.',
  'Masa respons: < 24 jam (hari bekerja)':
    'Response time: < 24 hours (working days)',
  'Masa respons: &lt; 24 jam (hari bekerja)':
    'Response time: < 24 hours (working days)',
  'Menunggu Pengesahan Pelanggan': 'Awaiting Customer Confirmation',
  'Menunggu pengesahan pelanggan': 'Awaiting customer confirmation',
  'Nilai Invois': 'Invoice Value',
  'Pembayaran Berjaya!': 'Payment Successful!',
  'Pembayaran Tidak Berjaya': 'Payment Failed',
  'Pembayaran anda mungkin berjaya tetapi pelan belum dikemas kini. Sila semak semula dalam beberapa saat atau hubungi sokongan jika masih belum berubah.':
    "Your payment may have succeeded but your plan hasn't updated yet. Please check again in a few seconds or contact support if it doesn't change.",
  'Pembayaran berjaya direkodkan!': 'Payment recorded successfully!',
  'Pembayaran tidak dapat diproses. Tiada bayaran akan dikenakan.':
    'Payment could not be processed. No charge will be made.',
  'Pratonton Resit': 'Receipt Preview',
  'Pratonton prestasi perniagaan anda': 'Preview your business performance',
  'Purata Nilai Invois': 'Average Invoice Value',
  'Resit Dijana': 'Receipt Generated',
  'Resit Pembayaran': 'Payment Receipt',
  'Resit berjaya dijana! WhatsApp telah dibuka.': 'Receipt generated! WhatsApp opened.',
  'Resit dijana tetapi gagal membuka WhatsApp':
    'Receipt generated but failed to open WhatsApp',
  'Ringkasan masalah anda...': 'Brief summary of your issue...',
  'Sebut Harga Dihantar': 'Quotation Sent',
  'Sebut Harga Diterima': 'Quotation Accepted',
  'Sebut harga berjaya dikemaskini!': 'Quotation updated successfully!',
  'Sebut harga dihantar!': 'Quotation sent!',
  'Sebut harga dihantar! Membuka WhatsApp...': 'Quotation sent! Opening WhatsApp...',
  'Sebut harga dipadam': 'Quotation deleted',
  'Sebut harga diterima!': 'Quotation accepted!',
  'Sebut harga ditolak': 'Quotation rejected',
  'Sebut harga perlu diterima dahulu': 'Quotation must be accepted first',
  'Sebut harga sudah wujud': 'Quotation already exists',
  'Sebut harga tidak dijumpai.': 'Quotation not found.',
  'Sebut harga yang ditolak tidak boleh diedit.':
    'Rejected quotations cannot be edited.',
  'Sebut harga yang ditolak tidak boleh diedit. Sila buat sebut harga baru.':
    'Rejected quotations cannot be edited. Please create a new quotation.',
  'Sedia untuk Work Order (pilihan)': 'Ready for Work Order (optional)',
  'Sedia untuk laporan': 'Ready for report',
  'Semak Semula Status': 'Re-check Status',
  'Semua kerja dan rekod': 'All jobs & records',
  'Semua pelanggan': 'All customers',
  'Semua sebut harga, work order dan invois':
    'All quotations, work orders & invoices',
  'Senarai semua invois yang telah dibayar': 'List of all paid invoices',
  'Status invois dikemaskini!': 'Invoice status updated!',
  'Tiket Berjaya Dihantar!': 'Ticket Submitted!',
  'Tiket telah ditutup. Terima kasih!': 'Ticket closed. Thank you!',
  'Tiket tidak dijumpai': 'Ticket not found',
  'Untuk Pelan Team Sahaja': 'Team Plan Only',
  'Upgrade ke Pro untuk akses sistem referral':
    'Upgrade to Pro to access the referral system',
  'Upgrade ke Pro untuk menggunakan bulan percuma anda.':
    'Upgrade to Pro to use your free months.',
  'Wajib — min 1 gambar': 'Required — minimum 1 photo',
  'Work Order aktif sudah wujud': 'An active Work Order already exists',
  'Work Order dipadam': 'Work Order deleted',
  'Work order dibuat dari halaman kerja selepas sebut harga diterima.':
    'Work orders are created from the job page after the quotation is accepted.',
  'Anda dijemput oleh rakan kontraktor WorkTrace!':
    'You were invited by a WorkTrace contractor!',
  'Daftar sekarang dan nikmati ciri-ciri premium WorkTrace.':
    'Sign up now and enjoy WorkTrace premium features.',
  'Tanya apa sahaja tentang cara menggunakan WorkTrace. Kami akan bantu anda 24/7.':
    'Ask anything about using WorkTrace. We help you 24/7.',
  'Terangkan masalah anda dengan terperinci. Sertakan:\n• Apa yang anda cuba lakukan\n• Apa yang berlaku\n• Bila ia berlaku':
    'Describe your issue in detail. Include:\n• What you were trying to do\n• What happened\n• When it happened',
  'Terima notifikasi pada telefon atau komputer anda apabila pelanggan mengesahkan/menolak dokumen,':
    'Get notifications on your phone or computer when customers confirm/reject documents,',
  'menghantar bukti pembayaran, atau pasukan sokongan membalas tiket anda.':
    'send payment proof, or our support team replies to your tickets.',
  'Pendaftaran Akaun': 'Account Registration',
  'Profil disimpan!': 'Profile saved!',
  'Selamat datang ke WorkTrace': 'Welcome to WorkTrace',
  'Siapkan profil anda': 'Set up your profile',
  '+ Tambah fail (maks 3, 5MB setiap satu)': '+ Add file (max 3, 5MB each)',
  '(Tiada nombor)': '(No number)',
  'baru sahaja': 'just now',
  'bulan': 'month',
  'kerja': 'job',
  'pelanggan': 'customer',
  'invois': 'invoice',
  'sebut harga': 'quotation',
  'untuk pending. Teks biasa dikira siap.': 'for pending. Plain text counts as done.',
  'untuk siap,': 'for done,',
  ', sila taip': ', please type',
  '. Untuk menukar status kepada': '. To change status to',
  '⏱ Anda ada': '⏱ You have',
  'untuk membatalkan sebelum data dipadam kekal.':
    'to cancel before data is permanently deleted.',
  '⏳ Menunggu pelanggan muat naik bukti pembayaran.':
    '⏳ Waiting for customer to upload payment proof.',
  '✓ Laporan Siap Kerja telah dihantar': '✓ Completion Report has been sent',
  '✓ Work Order Diterima — Kerja boleh dimulakan':
    '✓ Work Order Accepted — Job can begin',
  '✕ Memadam semua kerja dan pelanggan': '✕ Delete all jobs & customers',
  '✕ Memadam semua quotation & invois': '✕ Delete all quotations & invoices',
  '✕ Memadam semua work order & laporan': '✕ Delete all work orders & reports',
  '✕ Membatalkan langganan Pro anda': '✕ Cancel your Pro subscription',
  '🐛 Bug / Ralat Teknikal': '🐛 Bug / Technical Error',
  '👤 Akaun': '👤 Account',
  '👤 Masalah Akaun': '👤 Account Issue',
  '👥 Pelanggan': '👥 Customers',
  '💡 Cadangan Ciri Baru': '💡 Feature Request',
  '💡 Sebelum memadam, pertimbangkan:': '💡 Before deleting, consider:',
  '📄 Sebut Harga': '📄 Quotation',
  '📋 Kerja': '📋 Jobs',
  '📥 Bukti Pembayaran Diterima — Sila Sahkan':
    '📥 Payment Proof Received — Please Confirm',
  '📧 Hantar Tiket Sokongan': '📧 Submit Support Ticket',
  '📷 Gambar Sebelum Kerja': '📷 Before Photos',
  '📷 Gambar Selepas Kerja': '📷 After Photos',
  '📷 Laporan Siap': '📷 Completion Photos',
  '🤖 AI Bantuan akan datang tidak lama lagi! Gunakan tiket sokongan untuk pertanyaan sekarang.':
    '🤖 AI Help is coming soon! Use a support ticket for questions for now.',
  '🧾 Invois': '🧾 Invoice',
  '🧾 Resit': '🧾 Receipt',
  'Ciri multi-pengguna untuk pelan Agency akan datang tidak lama lagi. Anda akan dapat menjemput ahli pasukan,':
    'Multi-user features for the Agency plan are coming soon. You will be able to invite team members,',
  'menetapkan peranan, dan mengurus akses.': 'assign roles, and manage access.',
  'Sebelum tarikh tersebut, anda boleh:': 'Before that date, you can:',
  '• Log masuk dan batalkan permintaan': '• Log in and cancel the request',
  '• Dengan tahun:': '• With year:',
  '— Aktif ●': '— Active ●',
  '/bulan': '/month',
  '/tahun': '/year',
  'daripada program rujukan! Akan digunakan': 'from the referral program! Will be applied',
  'semasa pembaharuan langganan.': 'on your next renewal.',
  '1 bulan percuma': '1 month free',
  '14 hari': '14 days',
  '3 Bulan': '3 Months',
  '5 Pelanggan Teratas': 'Top 5 Customers',
  'di bawah untuk mengesahkan. Nombor resit yang dijana mungkin tidak sah selepas perubahan ini.':
    'below to confirm. Generated receipt numbers may become invalid after this change.',
  'untuk mengesahkan:': 'to confirm:',
  'hanya boleh diedit pada pelan': 'can only be edited on the',
  'hanya tersedia untuk pengguna pelan': 'is only available to users on the',
  'e.g. 2 hari, 1 minggu': 'e.g. 2 days, 1 week',
  'PDF berjaya dijana! WhatsApp telah dibuka.':
    'PDF generated! WhatsApp opened.',
  'Pautan pengesahan dijana! WhatsApp telah dibuka.':
    'Confirmation link generated! WhatsApp opened.',
  'Nyatakan sebab penolakan. Pelanggan perlu hantar semula.':
    'State the reason for rejection. The customer must resubmit.',
  'Pemadaman akaun dibatalkan!': 'Account deletion cancelled!',
  'Gagal batalkan pemadaman': 'Failed to cancel deletion',
  '— Aktif': '— Active',
  '✓ Laporan Siap Kerja telah dihantar dan menunggu pengesahan pelanggan':
    '✓ Completion Report sent and awaiting customer confirmation',
};
