-- English versions of user terms & conditions (Malay stays in the existing columns)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS quotation_terms_en text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS invoice_terms_en text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS wo_terms_en text;

-- Backfill English versions from existing terms (users can edit later)
-- Terms already written in English: copy as-is
UPDATE public.profiles SET quotation_terms_en = quotation_terms
 WHERE quotation_terms_en IS NULL AND md5(quotation_terms) IN ('2f631ff6b1b17a83692465dfb9fbc7d2','3f7ce7549fafa7a883a01a91e7d3de6c');
UPDATE public.profiles SET invoice_terms_en = invoice_terms
 WHERE invoice_terms_en IS NULL AND md5(invoice_terms) = '20df8520096af988d09c3f8a16789f44';

UPDATE public.profiles SET quotation_terms_en = $t$1. This quotation is valid for 30 days from the date of issue.
2. Prices are subject to change without notice.
3. A deposit payment is required before work commences.
4. Work will only begin after the deposit has been received in full.
5. Any additional work (variation work) will be charged separately.
6. The completion period depends on site conditions, weather, and factors beyond control.
7. The client shall ensure the work site is accessible and safe for work execution.
8. Any late payment may cause work to be postponed.
9. This quotation is based solely on the stated scope of work.$t$
 WHERE quotation_terms_en IS NULL AND md5(quotation_terms) = '180490c8d3cf2be26e75ae1a8311b70c';

UPDATE public.profiles SET quotation_terms_en = $t$1. This quotation is valid for 30 days from the date above.
2. Prices are subject to change without notice.
3. A deposit payment is required before work commences.
4. Work will begin after the deposit is received.
5. Any additional work will be charged separately.$t$
 WHERE quotation_terms_en IS NULL AND md5(quotation_terms) = '4045707d44e34081aa2a3d9d40932504';

UPDATE public.profiles SET quotation_terms_en = $t$**QUOTATION TERMS & CONDITIONS**

1. This quotation is valid for **7 days** from the date of issue.

2. The prices stated are based on current costs and may change without prior notice in the event of increases in material prices, operating costs or external factors beyond our control.

3. A minimum deposit of **50%** of the quotation amount is mandatory before work commences.

4. Work will only begin after the deposit payment has been received in full and confirmed.

5. Any additional work or changes to the scope of work outside the original quotation will be charged separately and will only be carried out after obtaining written approval from the client.

6. The completion period is an estimate and is subject to site conditions, weather, material supply and other factors beyond our control.

7. The client is responsible for ensuring access to the work site and a safe environment throughout the work period.

8. Late payment may cause work to be postponed and the completion date will be adjusted according to current conditions.

9. This quotation only covers the stated scope of work. Any additional work or requests outside that scope will be charged separately after obtaining the client's approval.

10. Any cancellation of the order after work has started or materials have been ordered may be charged according to the costs incurred.

11. The warranty (if any) only covers installation defects or workmanship and does not cover damage due to misuse, natural disasters or modifications by other parties.

12. The 50% balance shall be paid in full upon completion of work or before project handover, unless agreed otherwise in writing by both parties.

13. Ownership of all goods supplied remains with MIN ASSET ENERGY LIFTING until payment is received in full.

---

**Thank you for the opportunity given to MIN ASSET ENERGY LIFTING. We appreciate your trust and hope to provide the best service.**

*This document is digitally generated by MIN ASSET ENERGY LIFTING and is an official company document. A signature or company stamp is not required unless required by contract or requested by any party.*
$t$
 WHERE quotation_terms_en IS NULL AND md5(quotation_terms) = 'cfaa30c577ceab76583296d406e32e29';

UPDATE public.profiles SET invoice_terms_en = $t$1. Please settle the payment within the specified period.
2. An official receipt will be issued after payment is received.
3. For enquiries, please contact us.
4. Late payment may incur additional charges.$t$
 WHERE invoice_terms_en IS NULL AND md5(invoice_terms) = '66525a77e46ccb4dbd8b0c9d170c264a';

UPDATE public.profiles SET invoice_terms_en = $t$1. This invoice is valid and must be paid within 14 days from the invoice date.
2. Payment shall be made to the company account as stated.
3. Any dispute must be notified within 7 days from the invoice date.
4. The company reserves the right to suspend work or services if payment is not received.
5. All payments made are non-refundable.
6. The client is fully responsible for the amount stated in this invoice.
7. Any additional costs not included in this invoice will be charged separately.
8. This invoice is based on the work/services that have been carried out.
9. By making payment, the client is deemed to agree to all the terms and conditions stated.$t$
 WHERE invoice_terms_en IS NULL AND md5(invoice_terms) = 'e0721a4a6f385f4da402d353fad2910d';

UPDATE public.profiles SET invoice_terms_en = $t$**INVOICE TERMS & CONDITIONS**

1. This invoice shall be settled according to the agreed payment method:

   * Credit Term: Payment shall be made within **14 days** from the invoice date to the company's official account.
   * Cash on Delivery (COD): Full payment shall be made before or upon delivery of goods. Delivery will only be completed after payment is confirmed.

2. Any dispute regarding the quantity, quality or amount of the invoice shall be notified in writing within **7 days** from the invoice date, or immediately upon delivery for COD transactions.

3. The company reserves the right to postpone, cancel or stop supply if payment is not made according to the agreed terms.

4. All payments received are final unless otherwise agreed in writing by the company.

5. Any work, delivery, service or additional charges not stated in this invoice will be charged separately.

6. This invoice is issued based on the supplies and/or services that have been provided. The risk of damage or loss passes to the client once delivery is completed.

7. If payment is not made upon delivery for COD transactions, the company reserves the right to postpone delivery, cancel the transaction or take any action deemed necessary to protect the company's interests.

8. By making payment or accepting the supplies and/or services, the client is deemed to have read, understood and agreed to all the terms and conditions stated.

9. Ownership of all goods supplied remains with MIN ASSET ENERGY LIFTING until payment is received in full.

10. The company is not responsible for any delays caused by weather, logistics disruptions, natural disasters, orders from authorities or other factors beyond the company's control.

11. Any amendment to the invoice or payment terms must be agreed in writing by both parties.

---

**Thank you for your payment and trust in MIN ASSET ENERGY LIFTING.**

*This document is digitally generated by MIN ASSET ENERGY LIFTING and is an official transaction record of the company. A signature or company stamp is not required unless required by contract or requested by any party.*
$t$
 WHERE invoice_terms_en IS NULL AND md5(invoice_terms) = 'f97e6077e06534324e4b3ec10f39dd69';