// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjzbgxooszxhqwyfgjsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqemJneG9vc3p4aHF3eWZnanNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NTExNDEsImV4cCI6MjA5MDMyNzE0MX0.3O5QhxVH5I4QUI6jlPlXPSaAX9pm3Ohk9hboFM1_qnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});